### ISSUE TITLE
Binary wheels for Windows

### ISSUE THREAD

**Issue by dahlia** [dulwich/dulwich#222]
Although Dulwich provides `setup.py install --pure` option, the option cannot be enabled when it’s installed as a dependency of `install_requires`, or using `pip install`.  On Windows which doesn’t have Visual Studio Dulwich installation fails without `--pure` option.

So it would be great if Dulwich provides binary [wheels](http://pythonwheels.com/) for Windows.

**Comment by jelmer** [comment]
Any news on this?

**Comment by garyvdm** [comment]
Actually started on this today. Will probably have a patch ready tomorrow.

**Comment by ankostis** [comment]
Having *wheels* autogenerated would be much appreciated.
It is possible to automate *Appveyor* to use [*twine*](https://pypi.org/project/twine/) to push wheels into PyPi, with an `appveyor.yml` like this:

```yaml
environment:
  PYPI_USER: "FOO"
  PYPI_PSWD:
    # See https://www.appveyor.com/docs/build-configuration/#secure-variables
    secure: <paste-your-encrypted-value>

#... regular build here

on_success:
  - ps: >-
      $cmtid = git rev-parse HEAD
      if (git describe --exact-match $cmtid) {
        twine upload -u PYPI_USER -p PYPI_PSWD dist/*
      }
```

Of course the situation becomes a bit more complex if gpg-signing is needed.
I could provide a PR but the user/password have to be set by the owner of the [PyPi account](https://pypi.org/project/dulwich/).
